name: gemini-fullstack-langgraph
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.12,<3.14
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly # Remove if GPU is needed, but this is a safer default for broad compatibility
  - faiss-cpu
  - pip:
    - langgraph
    - langchain
    - langchain-google-genai
    - python-dotenv
    - langgraph-sdk
    - langgraph-cli
    - langgraph-api
    - fastapi
    - google-genai
    - langchain-mcp-adapters
    - mcp
    - sentence-transformers
    - pandas
